//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauiMemoryGame.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MauiMemoryGame.Resources.Texts.TextsResource", typeof(TextsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attemps.
        /// </summary>
        public static string GameAttemps {
            get {
                return ResourceManager.GetString("GameAttemps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave the game without ending the game?.
        /// </summary>
        public static string GameBackQuestionMessage {
            get {
                return ResourceManager.GetString("GameBackQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit game.
        /// </summary>
        public static string GameBackQuestionTitle {
            get {
                return ResourceManager.GetString("GameBackQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is up and you haven&apos;t managed to discover all the pairs.
        /// </summary>
        public static string GameLoseSubtitle {
            get {
                return ResourceManager.GetString("GameLoseSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game over!!.
        /// </summary>
        public static string GameLoseTitle {
            get {
                return ResourceManager.GetString("GameLoseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairs.
        /// </summary>
        public static string GamePairs {
            get {
                return ResourceManager.GetString("GamePairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have discovered all the pairs before the time runs out.
        /// </summary>
        public static string GameWonSubtitle {
            get {
                return ResourceManager.GetString("GameWonSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!!.
        /// </summary>
        public static string GameWonTitle {
            get {
                return ResourceManager.GetString("GameWonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HighLevel {
            get {
                return ResourceManager.GetString("HighLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the level of difficulty with which you want to play.
        /// </summary>
        public static string LevelSelectorTitle {
            get {
                return ResourceManager.GetString("LevelSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LowLevel {
            get {
                return ResourceManager.GetString("LowLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MediumLevel {
            get {
                return ResourceManager.GetString("MediumLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play again.
        /// </summary>
        public static string PlayAgain {
            get {
                return ResourceManager.GetString("PlayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string ThemeSelectorDc {
            get {
                return ResourceManager.GetString("ThemeSelectorDc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marvel.
        /// </summary>
        public static string ThemeSelectorMarvel {
            get {
                return ResourceManager.GetString("ThemeSelectorMarvel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Simpsons.
        /// </summary>
        public static string ThemeSelectorSimpsons {
            get {
                return ResourceManager.GetString("ThemeSelectorSimpsons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star Wars.
        /// </summary>
        public static string ThemeSelectorStarWars {
            get {
                return ResourceManager.GetString("ThemeSelectorStarWars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the theme you want to play with.
        /// </summary>
        public static string ThemeSelectorTitle {
            get {
                return ResourceManager.GetString("ThemeSelectorTitle", resourceCulture);
            }
        }
    }
}
